/*
 * Wizard.java
 *
 * Created on July 27, 2007, 7:54 PM
 */

package faisal_TiLeD.adevgen.automatch.wizard;

import faisal_TiLeD.adevgen.matchingchecker.DTSScript.ComplexRect;
import faisal_TiLeD.adevgen.matchingchecker.DTSScript.DTSParser;
import faisal_TiLeD.adevgen.matchingchecker.DocumentsHolder;
import faisal_TiLeD.adevgen.matchingchecker.DrawingComponent;
import faisal_TiLeD.adevgen.matchingchecker.DrawingObject;
import java.io.File;
import java.util.Enumeration;
import java.util.Hashtable;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author  TV
 */
public class LayoutInfo extends JFrame {
    
    
    double L, W;
    double length, width;
    int type;
    
    String fullPath;
    String names[];
    int matrix[][];
    
    Hashtable<String, Double> values;
    Vector<ComplexRect> vRect;
    DTSParser parser;
    
    /** Creates new form Wizard
     * @param type
     * @param fullPath
     * @param L
     * @param W
     * @param names
     * @param matrix
     */
            
    public LayoutInfo(int type, String fullPath, double L, double W, String names[], int matrix[][]) {      
        this.type = type;
        this.fullPath = fullPath;
        this.L = L;
        this.W = W;
        this.names = names;
        this.matrix = matrix;
        parser = new DTSParser();
        initComponents();
        loadComponent();
    }
    
    
    
    public void loadComponent(){
        
        vRect = new Vector<ComplexRect>();        
        File file = new File(fullPath);
        
        try{
            //setCurrentComponent(new DrawingComponent(file.getName()));
            vRect = parser.getParsed(new String[]{file.getCanonicalPath(), ""+L, ""+W});
            values = parser.values;
            normalize();
            loadConstants();
            //addObjects(vRect);
        }catch(Exception e){
            e.printStackTrace();
        }
        
        file = null;
    }
    
    public void normalize(){
        int i,j;
        double left,top, right, bottom;
        
        //get left top
        left = vRect.get(0).left;
        top = vRect.get(0).top;
        right = vRect.get(0).right;
        bottom = vRect.get(0).bottom;
        for(i=1; i<vRect.size(); i++){
            if(left > vRect.get(i).left)
                left = vRect.get(i).left;
            if(top > vRect.get(i).top)
                top = vRect.get(i).top;
            
            if(right < vRect.get(i).right)
                right = vRect.get(i).right;
            if(bottom < vRect.get(i).bottom)
                bottom = vRect.get(i).bottom;            
        }
        length = right - left;
        width = bottom - top;
        
        left = -left;
        top = -top;
        for(i=0; i<vRect.size(); i++){
            vRect.get(i).left += left;
            vRect.get(i).right += left;
            vRect.get(i).top += top;
            vRect.get(i).bottom += top;
        }
        
        
        
        System.out.println("------------"+length+","+width);
    }
    
    public void loadConstants(){
        int i;
        String key;
        DTSParser rules = new DTSParser();
        rules.isRulesOnly = true;
        rules.getParsed(new String[]{fullPath, ""+L, ""+W});
        
        Hashtable<String, Double> hRules = rules.values;
        Enumeration<String> keys = hRules.keys();
        while(keys.hasMoreElements()){
            key = keys.nextElement();
            cboConstants.addItem(key+" : "+hRules.get(key));
            cboConstants1.addItem(key+" : "+hRules.get(key));
        }        
    }
//////    public void addObjects(int x, int y){
//////        int i,j;
//////        double left,top, right, bottom;
//////                
//////        for(i=0; i<vRect.size(); i++){
//////        /*
//////        addObjectToLayer(vRect.get(i).layer,
//////                (int)Math.round(vRect.get(i).left * lambda)+x,
//////                (int)Math.round(vRect.get(i).top * lambda)+y,
//////                (int)Math.round(vRect.get(i).getLength() * lambda),
//////                (int)Math.round(vRect.get(i).getWidth() * lambda));
//////         * */
//////        }
//////        //canvas.repaint();
//////        
//////    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtManual = new javax.swing.JTextField();
        rdoManual = new javax.swing.JRadioButton();
        rdoAutomatic = new javax.swing.JRadioButton();
        chkNegative = new javax.swing.JCheckBox();
        cboConstants = new javax.swing.JComboBox();
        btnAdd = new javax.swing.JButton();
        txtConstants = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        rdoManual1 = new javax.swing.JRadioButton();
        txtManual1 = new javax.swing.JTextField();
        rdoAutomatic1 = new javax.swing.JRadioButton();
        chkNegative1 = new javax.swing.JCheckBox();
        cboConstants1 = new javax.swing.JComboBox();
        btnAdd1 = new javax.swing.JButton();
        txtConstants1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblTotal1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Wizard: Specification");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Finish");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Previous");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(483, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(33, 33, 33))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2, jButton3});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setForeground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Verdana", 2, 36));
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Layout Info");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(388, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jLabel2.setText("Please Enter the Gap Between Parts: (in Micron)");

        buttonGroup1.add(rdoManual);
        rdoManual.setText("Manual");
        rdoManual.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        rdoManual.setMargin(new java.awt.Insets(0, 0, 0, 0));

        buttonGroup1.add(rdoAutomatic);
        rdoAutomatic.setSelected(true);
        rdoAutomatic.setText("Automatic");
        rdoAutomatic.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        rdoAutomatic.setMargin(new java.awt.Insets(0, 0, 0, 0));

        chkNegative.setText("Negative");
        chkNegative.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chkNegative.setMargin(new java.awt.Insets(0, 0, 0, 0));
        chkNegative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkNegativeActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        txtConstants.setOpaque(false);

        jLabel3.setText("=");

        buttonGroup2.add(rdoManual1);
        rdoManual1.setText("Manual");
        rdoManual1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        rdoManual1.setMargin(new java.awt.Insets(0, 0, 0, 0));

        buttonGroup2.add(rdoAutomatic1);
        rdoAutomatic1.setSelected(true);
        rdoAutomatic1.setText("Automatic");
        rdoAutomatic1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        rdoAutomatic1.setMargin(new java.awt.Insets(0, 0, 0, 0));

        chkNegative1.setText("Negative");
        chkNegative1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chkNegative1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        chkNegative1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkNegative1ActionPerformed(evt);
            }
        });

        btnAdd1.setText("Add");
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });

        txtConstants1.setOpaque(false);

        jLabel4.setText("=");

        jLabel5.setText("Horizontal Gap");

        jLabel6.setText("Vertical Gap");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkNegative)
                                    .addComponent(cboConstants, 0, 143, Short.MAX_VALUE)
                                    .addComponent(txtManual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAdd))
                            .addComponent(txtConstants, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rdoAutomatic)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdoManual)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkNegative1)
                                    .addComponent(txtManual1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                    .addComponent(cboConstants1, 0, 143, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAdd1))
                            .addComponent(txtConstants1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rdoAutomatic1)
                    .addComponent(rdoManual1)
                    .addComponent(jLabel6))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoManual1)
                        .addGap(5, 5, 5)
                        .addComponent(txtManual1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoAutomatic1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkNegative1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd1)
                            .addComponent(cboConstants1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtConstants1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(lblTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoManual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtManual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoAutomatic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkNegative)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd)
                            .addComponent(cboConstants, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtConstants, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-823)/2, (screenSize.height-394)/2, 823, 394);
    }// </editor-fold>//GEN-END:initComponents

private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
    String Cons = ((String)cboConstants1.getSelectedItem()).split(" : ")[0];
    if(txtConstants1.getText().equals("")){
        txtConstants1.setText(Cons);        
    }else{
        txtConstants1.setText(txtConstants1.getText()+"+"+Cons);        
    }
    double value = getVerticalGap();
    lblTotal1.setText(value+"");
}//GEN-LAST:event_btnAdd1ActionPerformed

private void chkNegative1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNegative1ActionPerformed
    double value = getVerticalGap();
    lblTotal1.setText(value+"");
}//GEN-LAST:event_chkNegative1ActionPerformed

private void chkNegativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNegativeActionPerformed
    double value = getHorizontalGap();
    lblTotal.setText(value+"");
}//GEN-LAST:event_chkNegativeActionPerformed

private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
    String Cons = ((String)cboConstants.getSelectedItem()).split(" : ")[0];
    if(txtConstants.getText().equals("")){
        txtConstants.setText(Cons);        
    }else{
        txtConstants.setText(txtConstants.getText()+"+"+Cons);        
    }
    double value = getHorizontalGap();
    lblTotal.setText(value+"");
}//GEN-LAST:event_btnAddActionPerformed
    
public double getHorizontalGap(){
    
    if(rdoManual.isSelected()){
        return Double.parseDouble(txtManual.getText());
    }
    
    double value = parser.evaluate(txtConstants.getText(), values);
    
    if(chkNegative.isSelected())
        value = -value;
    
    return value;
}    

public double getVerticalGap(){
    
    if(rdoManual1.isSelected()){
        return Double.parseDouble(txtManual1.getText());
    }
    double value = parser.evaluate(txtConstants1.getText(), values);
    
    if(chkNegative1.isSelected())
        value = -value;
    
    return value;
}   

public DrawingComponent getDefaultComponent(){
    DrawingComponent dc = new DrawingComponent("Default");
    int i;
    ComplexRect cr;
    DrawingObject dobj;
    DocumentsHolder dh = DocumentsHolder.getDefaultApp();
    double lambda = DocumentsHolder.lambda;
    for(i=0; i<vRect.size(); i++){
        cr = vRect.get(i);
        dobj = new DrawingObject(cr.left * lambda, cr.top * lambda, (cr.right - cr.left) * lambda, (cr.bottom - cr.top) * lambda, dh.types[cr.layer]);
        dc.element.add(dobj);
    }
    dc.left = 0;
    dc.top = 0;
    dc.length = length * DocumentsHolder.lambda;
    dc.width = width * DocumentsHolder.lambda;
    return dc;
}

private void generateComponentSeries(){
    DrawingComponent dc = getDefaultComponent();
    Vector<DrawingComponent> vDC = new Vector<DrawingComponent>();
    DrawingComponent tdc;
    
    
    int i,j;
    double left=1, top=1;
    double hgap;
    double vgap;
    try{
        hgap = getHorizontalGap();
        vgap = getVerticalGap();
    }catch(Exception e){
        return;
    }
    
    DocumentsHolder.getDefaultApp().newDocuments();
    DocumentsHolder.getDefaultApp().defaultComponent();
    for(i=0; i<matrix.length; i++){
        for(j=0; j<matrix[0].length; j++){
            if(!names[matrix[i][j]].equals("dummy")){
                tdc = dc.clone(names[matrix[i][j]]);
                tdc.move(left * DocumentsHolder.lambda, top * DocumentsHolder.lambda);
                vDC.add(tdc);
            }
            left = left + length + hgap; 
        }
        left = 1;
        top = top + width + vgap;
    }
    
    DocumentsHolder.getDefaultApp().vComp = vDC;
    DocumentsHolder.getDefaultApp().refresh();
    
}

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    dispose();
    Wizard.wizard.setVisible(true);
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
    generateComponentSeries();
    
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    dispose();
}//GEN-LAST:event_jButton1ActionPerformed

/**
 * @param args the command line arguments
 */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAdd1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox cboConstants;
    private javax.swing.JComboBox cboConstants1;
    private javax.swing.JCheckBox chkNegative;
    private javax.swing.JCheckBox chkNegative1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotal1;
    private javax.swing.JRadioButton rdoAutomatic;
    private javax.swing.JRadioButton rdoAutomatic1;
    private javax.swing.JRadioButton rdoManual;
    private javax.swing.JRadioButton rdoManual1;
    private javax.swing.JTextField txtConstants;
    private javax.swing.JTextField txtConstants1;
    private javax.swing.JTextField txtManual;
    private javax.swing.JTextField txtManual1;
    // End of variables declaration//GEN-END:variables
    
}
