/*
 * GraphicsTest.java
 *
 * Created on March 20, 2007, 8:43 AM
 */

package faisal_TiLeD.adevgen.matchingchecker;

import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author  Administrator
 */
public class GraphicsTest extends javax.swing.JPanel {
    int state=0;
    /** Creates new form GraphicsTest */
    public GraphicsTest() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(277, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        state--;
        repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        state++;
        repaint();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void paint(Graphics g){
        super.paint(g);
        Graphics2D g2 = (Graphics2D)g;
        g2.drawString(""+state, 20,40);
        switch(state){
            case 1:
                //g2.translate(-50,-50);
                //g2.drawRect(100,100,100,100);
                g2.translate(50,50);
                g2.drawRect(0,0,100,100);
                g2.scale(.5,.5);
                g2.drawRect(0,0,100,100);
                g2.drawLine(0,0,300,0);
                g2.drawLine(0,0,0,300);
                break;
            case 2:
                //g2.translate(-50,-50);
                //g2.drawRect(100,100,100,100);
                g2.scale(.5,.5);
                g2.drawRect(0,0,100,100);
                g2.translate(50,50);
                g2.drawRect(0,0,100,100);
                g2.drawLine(0,0,300,0);
                g2.drawLine(0,0,0,300);
                break; 
            case 3:
                g2.translate(-150,-150);
                
                g2.drawRect(100,100,100,100);
                g2.drawLine(0,0,300,0);
                g2.drawLine(0,0,0,300);
                break; 
           case 4:
                g2.translate(-150,-150);
                g2.drawRect(100,100,100,100);
                g2.translate(150,150);
                g2.drawLine(0,0,300,0);
                g2.drawLine(0,0,0,300);
                
                break;     
           case 5:
                g2.scale(.5,.5);
                g2.translate(150,150);
                g2.drawRect(100,100,100,100);
                g2.drawLine(0,0,300,0);
                g2.drawLine(0,0,0,300);
                break;
           case 6:
                g2.scale(.5,.5);
                g2.translate(-150,-150);
                g2.drawRect(100,100,100,100);
                g2.drawLine(0,0,300,0);
                g2.drawLine(0,0,0,300);
                break;
            case 7:
                g2.translate(-150,-150);
                g2.scale(.5,.5);
                g2.drawRect(100,100,100,100);
                g2.drawLine(0,0,300,0);
                g2.drawLine(0,0,0,300);
                break; 
                
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
    
}
