/*
 * GUIContainer.java
 *
 * Created on June 15, 2007, 2:39 PM
 */

package faisal_TiLeD.adevgen.gui;

import faisal_TiLeD.adevgen.database.LayerDatabase;
import faisal_TiLeD.adevgen.datastructure.DataManager;
import faisal_TiLeD.adevgen.datastructure.Device;
import faisal_TiLeD.adevgen.datastructure.Layer;
import faisal_TiLeD.adevgen.datastructure.MaskRectangle;
import faisal_TiLeD.adevgen.datastructure.Rectangle;

import faisal_TiLeD.adevgen.graph.DeviceGraph;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.util.Vector;
import javax.swing.JCheckBox;
import javax.swing.JToggleButton;

/**
 *
 * @author  Administrator
 */
public class GUIContainer extends javax.swing.JFrame implements DrawingStatusListener {
    Rectangle rec = null;
    Layer currentLayer = null;
    Device currentDevice= null;
    /** Creates new form GUIContainer */
    public GUIContainer() {
        initComponents();
        dt.setDsl(this);    //Listener
        loadLayers();
        currentDevice = DataManager.getDm().getCurrentDevice();
        
    }
    
    public void loadLayers(){
        LayerDatabase ld = new LayerDatabase();
        Vector<Layer> layers = ld.getLayersList();
        
        
        pnLayers.setLayout(new GridLayout(layers.size(), 2));
        JToggleButton jtb[] = new JToggleButton[layers.size()];
        JCheckBox jcb[] = new JCheckBox[layers.size()];
        //ButtonGroup bg = new ButtonGroup();
        int i, k = 0;
        Layer layer;
        for(i=0; i<layers.size(); i++){
            
            layer = layers.get(i);
            jtb[i] = new JToggleButton(layer.getLayerName());
            jtb[i].addActionListener(new SelectLayerListener(i, new FunctionCallListener(){
                
                public void selectLayer(ActionEvent e, int index) {
                    currentLayer = DataManager.getLm().get(index);
                    dt.setColor(currentLayer.getColor());
                }
                
            }));
            
            jcb[i] = new JCheckBox("GDSII: "+layer.getLayerID());
            jcb[i].setSelected(true);
            jcb[i].addActionListener(new SelectLayerListener(k, new FunctionCallListener(){
                
                public void selectLayer(ActionEvent e, int index) {
                    if(((JCheckBox)e.getSource()).isSelected()){
                        DataManager.getLm().get(index).setVisible(true);
                    }else{
                        DataManager.getLm().get(index).setVisible(false);
                    }
                    dt.repaint();
                }
                
            }));
            
            bg.add(jtb[i]);
            pnLayers.add(jtb[i]);
            pnLayers.add(jcb[i]);
        }
        
        jtb[0].setSelected(true);
        currentLayer = DataManager.getLm().get(0);
        dt.setColor(currentLayer.getColor());
    }
    
    public void selectLayer(int index){
        
    }
    
    public void drawStarted(int x, int y){
        if(tglVariableMask.isSelected()){
            rec = new MaskRectangle();
        }
        else{
            rec = new Rectangle();
        }
        
        
        rec.setLocation(x, y);
    }
    public void drawFinished(int x, int y){
        int a,b,c,d;
        
        if(rec.getX() < x) {
            a = (int) rec.getX();
            b = x;
        }else{
            a = x;
            b = (int) rec.getX();
        }
        
        if(rec.getY() < y){
            c = (int) rec.getY();
            d = y;
        }else{
            c = y;
            d = (int) rec.getY();
        }
        
        if(b-a + d-c < 1){
            rec = null;
            return;
        }
        
        rec.setLocation(a, c);
        rec.setSize(b-a+1, d-c+1);
        
        if(tglVariableMask.isSelected()){
            new MaskDetails(this, true, (MaskRectangle)rec);
        }
        //currentLayer = DataManager.getLm().get(0);
        //currentDevice = DataManager.getDm().getCurrentDevice();
        
        DataManager.addRectangle(rec, currentLayer, currentDevice);
        
    }
    public void drawCanceled(){
        rec = null;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        dt = new faisal_TiLeD.adevgen.gui.DeviceTemplate();
        jPanel1 = new javax.swing.JPanel();
        pnLayers = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtXGrid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtYGrid = new javax.swing.JTextField();
        btnReGrid = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        tglVariableMask = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Analog Device Generator");
        getContentPane().add(dt, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(pnLayers, java.awt.BorderLayout.PAGE_START);

        jLabel1.setText("X Grid: ");

        jLabel2.setText("Y Grid: ");

        btnReGrid.setText("Re Grid");
        btnReGrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReGridActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        bg.add(tglVariableMask);
        tglVariableMask.setText("Mask");
        tglVariableMask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglVariableMaskActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tglVariableMask, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtYGrid, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtXGrid, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                        .addGap(14, 14, 14))
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(btnReGrid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                .addGap(77, 77, 77))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tglVariableMask)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtXGrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtYGrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReGrid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addContainerGap(357, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-800)/2, (screenSize.height-550)/2, 800, 550);
    }// </editor-fold>//GEN-END:initComponents
    
private void tglVariableMaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglVariableMaskActionPerformed
    currentLayer = DataManager.getLm().getMaskLayer();
    dt.setColor(currentLayer.getColor());
}//GEN-LAST:event_tglVariableMaskActionPerformed

private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
    DeviceGraph dg = new DeviceGraph(currentDevice, DeviceGraph.X_GRAPH);
}//GEN-LAST:event_btnSaveActionPerformed

private void btnReGridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReGridActionPerformed
    dt.reGrid(Integer.parseInt(txtXGrid.getText()), Integer.parseInt(txtYGrid.getText()));
}//GEN-LAST:event_btnReGridActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new GUIContainer().setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg;
    private javax.swing.JButton btnReGrid;
    private javax.swing.JButton btnSave;
    private faisal_TiLeD.adevgen.gui.DeviceTemplate dt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel pnLayers;
    private javax.swing.JToggleButton tglVariableMask;
    private javax.swing.JTextField txtXGrid;
    private javax.swing.JTextField txtYGrid;
    // End of variables declaration//GEN-END:variables
    
}
