/*
 * LayeredCanvas.java
 *
 * Created on June 16, 2007, 8:32 AM
 */

package faisal_TiLeD.adevgen.gui;


import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JLayeredPane;

/**
 *
 * @author  Administrator
 */
public class LayeredCanvas extends JLayeredPane {
    int x=40, y=40;
    /** Creates new form BeanForm */
    public LayeredCanvas() {
        initComponents();
        
        ndp.setVisible(false);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        ndp = new faisal_TiLeD.adevgen.gui.NewDevicePane();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        ndp.setBounds(20, 20, 300, 90);
        add(ndp, javax.swing.JLayeredPane.DEFAULT_LAYER);
    }// </editor-fold>//GEN-END:initComponents

private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
    
     if(evt.getButton() != evt.BUTTON1){                
        int x, y;
        x = evt.getX()+5;
        if(x + ndp.getWidth()+5 >= getWidth())
            x -= ndp.getWidth() - 10;
        y = evt.getY()+5;
        if(y + ndp.getHeight()+5 >= getHeight())
            y -= ndp.getHeight() - 10;
        ndp.setLocation(x, y);
        ndp.setVisible(true);
    }                                               
    
}//GEN-LAST:event_formMousePressed
    public void paint(Graphics g){
        super.paint(g);
        int i, j=100;
        g.setColor(new Color(0,50,250,20));
        g.fillRect(40, 40, getWidth()-40, getHeight()-40);
        g.setColor(new Color(250,50,50));
        g.drawRect(x, y, x, y);
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private faisal_TiLeD.adevgen.gui.NewDevicePane ndp;
    // End of variables declaration//GEN-END:variables
    
}
