/*
 * NewDevicePane.java
 *
 * Created on June 16, 2007, 9:09 AM
 */

package faisal_TiLeD.adevgen.gui;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JLayeredPane;

/**
 *
 * @author  Administrator
 */
public class NewDevicePane extends JLayeredPane {
    private int tempX;
    private int tempY;
    private boolean isDragged = false;
  
    /** Creates new form BeanForm */
    public NewDevicePane() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboDevices = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        txtWidth = new javax.swing.JTextField();
        txtHeight = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();

        cboDevices.setBounds(10, 30, 140, 20);
        add(cboDevices, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setText("Devices");
        jLabel1.setBounds(10, 10, 90, 14);
        add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txtWidth.setBounds(170, 30, 50, 20);
        add(txtWidth, javax.swing.JLayeredPane.DEFAULT_LAYER);
        txtHeight.setBounds(230, 30, 50, 20);
        add(txtHeight, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setText("Width");
        jLabel2.setBounds(170, 10, 50, 14);
        add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setText("Height");
        jLabel3.setBounds(230, 10, 50, 14);
        add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnOK.setText("=");
        btnOK.setBounds(230, 60, 50, 23);
        add(btnOK, javax.swing.JLayeredPane.DEFAULT_LAYER);
    }// </editor-fold>//GEN-END:initComponents
    
    public void paint(Graphics g){
        g.setColor(new Color(0,200,0));
        g.drawRoundRect(0, 0, getWidth()-1, getHeight()-1, 40,20);
        g.setColor(new Color(0,100,0));
        g.drawRoundRect(2, 2, getWidth()-5, getHeight()-5, 40,20);
        g.setColor(new Color(40,250,30,70));
        g.fillRoundRect(0, 0, getWidth(), getHeight(), 40,20);
        super.paint(g);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JComboBox cboDevices;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtWidth;
    // End of variables declaration//GEN-END:variables
    
}
